### ISSUE TITLE
Qt5.15 not available

### ISSUE THREAD

**Issue by FrenchGithubUser** [varlesh/focal-packages#1]
I tried to install nulloy on pop os 20.4 but I get this error : 

`nulloy: /lib/x86_64-linux-gnu/libQt5Core.so.5: version 'Qt_5.15' not found (required by nulloy)`

(ofc the .deb package that you provide)

**Comment by varlesh** [comment]
updated

**Comment by FrenchGithubUser** [comment]
Yes it works, thanks!
